# board
board_delay_seconds = 1
board_rows = 5
board_columns = 5

# herbivore
herbivore_speed = 1
herbivore_hp = 1
herbivore_max_steps_hungry_before_die = 5
herbivore_nutrition_value = 1
herbivore_sign = " ğŸ¦™ "
herbivore_spawn_rate = 0.3

# predator
predator_speed = 2
predator_hp = 1
predator_max_steps_hungry_before_die = 5
predator_attack_power = 1
predator_sign = " ğŸ¦ï¸ "
predator_spawn_rate = 0.1

# grass
grass_sign = " â˜˜ï¸ "
grass_nutrition_value = 1
grass_spawn_rate = 0.3

# rock
rock_sign = " ğŸª¨ "
rock_spawn_rate = 0.1

# tree
tree_sign = " ğŸŒ³ "
tree_spawn_rate = 0.1
